### ISSUE TITLE
Do actual parsing

### ISSUE THREAD

**Issue by mattfbacon** [lino-levan/tlpack#1]
Regular expressions are not suitable for parsing grammars. You can use a ready-made JavaScript/TypeScript parser such as [Esprima](https://esprima.org/) to get an actual parse tree.

Your regular expressions to match import statements do not work with:

- Strings (`"import bar from 'foo'"`)
- Comments (`/* import bar from 'foo' */`)
- Escape codes (`import bar from 'f\'oo'`)
- Mismatched quotes (`import bar from "foo'`)
- Bad grammar (`import bar a bunch of (#(*^ran(*&dom J*<@S symbol$(*&!(s or #(*&something from foo`)
- Whitespace (`import  bar    from     'foo'`)
- Other weird cases (`import { "from 'foo'": bar } from 'foo'`)
- Greedy RegExp repetition operators
- Etc

The output from a parser like Esprima is fairly easy to work with. Probably more so than regular expressions.

**Comment by lino-levan** [comment]
Done. `esprima` is an abandoned library so I am using `exprima-next` but other than that, thanks for the tip!
